#!/bin/bash
# LXC Network Isolation Setup
# Generated by KIVA-CLI Phase 5 Batch 3/3
# Mode: H0 Autonomous Base-3 Ternary
# IntentHash: 0x6F8E3D2A9C5B1E4A-F11468A80A92-NET-ISO

set -euo pipefail

BRIDGE_NAME="lxcbr0"
BRIDGE_IP="10.0.3.1"
BRIDGE_NETMASK="255.255.255.0"
BRIDGE_NETWORK="10.0.3.0/24"
BRIDGE_DHCP_RANGE="10.0.3.2,10.0.3.254"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    log_error "Please run as root"
    exit 1
fi

log_info "Starting LXC Network Isolation Setup"

# 1. Create bridge if not exists
if ! ip link show $BRIDGE_NAME &> /dev/null; then
    log_info "Creating bridge $BRIDGE_NAME"
    brctl addbr $BRIDGE_NAME
    ip addr add $BRIDGE_IP/${BRIDGE_NETMASK#*.*.*.} dev $BRIDGE_NAME
    ip link set $BRIDGE_NAME up
else
    log_warn "Bridge $BRIDGE_NAME already exists"
fi

# 2. Setup NAT for internet access
log_info "Configuring NAT for container internet access"
iptables -t nat -A POSTROUTING -s $BRIDGE_NETWORK ! -d $BRIDGE_NETWORK -j MASQUERADE

# 3. Enable IP forwarding
log_info "Enabling IP forwarding"
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf

# 4. Setup firewall rules - Default deny, explicit allow
log_info "Configuring firewall rules"

# Flush existing rules
iptables -F FORWARD

# Default policy: DROP
iptables -P FORWARD DROP

# Allow established connections
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow container to container communication within same VLAN
iptables -A FORWARD -i $BRIDGE_NAME -o $BRIDGE_NAME -j ACCEPT

# Allow specific outbound ports (HTTP, HTTPS, DNS, NTP)
iptables -A FORWARD -i $BRIDGE_NAME -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -i $BRIDGE_NAME -p tcp --dport 443 -j ACCEPT
iptables -A FORWARD -i $BRIDGE_NAME -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -i $BRIDGE_NAME -p udp --dport 123 -j ACCEPT

# Deny all other outbound traffic
iptables -A FORWARD -i $BRIDGE_NAME -j LOG --log-prefix "LXC-BLOCKED: "
iptables -A FORWARD -i $BRIDGE_NAME -j DROP

# 5. Setup VLAN segmentation
log_info "Configuring VLAN segmentation"

# VLAN 10: Critical services (kiva-cli, brain, fluence)
ip link add link $BRIDGE_NAME name ${BRIDGE_NAME}.10 type vlan id 10
ip link set ${BRIDGE_NAME}.10 up

# VLAN 20: Application services (candidator, geribooking)
ip link add link $BRIDGE_NAME name ${BRIDGE_NAME}.20 type vlan id 20
ip link set ${BRIDGE_NAME}.20 up

# VLAN 30: Utility services (devtools, email-sender)
ip link add link $BRIDGE_NAME name ${BRIDGE_NAME}.30 type vlan id 30
ip link set ${BRIDGE_NAME}.30 up

# 6. Setup DNS resolution
log_info "Configuring DNS resolution via dnsmasq"
cat > /etc/dnsmasq.d/lxc-containers.conf <<EOF
# LXC DNS Configuration
interface=$BRIDGE_NAME
bind-interfaces
dhcp-range=$BRIDGE_DHCP_RANGE,12h
dhcp-option=option:router,$BRIDGE_IP

# Static DHCP mappings per container
dhcp-host=kiva-cli,10.0.3.10
dhcp-host=ecoystem,10.0.3.11
dhcp-host=devtools,10.0.3.12
dhcp-host=candidator,10.0.3.13
dhcp-host=racines,10.0.3.14
dhcp-host=email-sender,10.0.3.15
dhcp-host=fluence,10.0.3.16
dhcp-host=brain,10.0.3.17
dhcp-host=bank-buster,10.0.3.18
dhcp-host=geribooking,10.0.3.19
dhcp-host=brain-docs,10.0.3.20

# Local DNS resolution
local=/lxc/
domain=lxc
EOF

systemctl restart dnsmasq

# 7. Persist iptables rules
log_info "Persisting iptables rules"
iptables-save > /etc/iptables/rules.v4

log_info "✅ LXC Network Isolation Setup Complete"
log_info "Bridge: $BRIDGE_NAME ($BRIDGE_IP/${BRIDGE_NETMASK#*.*.*.})"
log_info "VLAN 10: Critical (10.0.3.10-19)"
log_info "VLAN 20: Applications (10.0.3.20-29)"
log_info "VLAN 30: Utilities (10.0.3.30-39)"

exit 0
