#!/usr/bin/env python3
# fmt: off
"""
generate_rules.py — BRGS L3: Generate bash rules from governance manifest.

Reads the branch_routing section of multi-repo-governance.yaml and produces
a .githooks/rules.sh file with bash variables sourced by the pre-push hook.

Usage:
    python generate_rules.py <manifest_path> <repo_name> <output_rules.sh>

Arguments:
    manifest_path  — Path to multi-repo-governance.yaml
    repo_name      — Name of the current repository (must match manifest key)
    output_rules   — Path to write rules.sh (typically .githooks/rules.sh)

Output (rules.sh):
    FORBIDDEN_PATHS="path1|path2|..."
    ALLOWED_PREFIXES="prefix1|prefix2|..."
    REDIRECT_MAP="src/repo1/:gerivdb/REPO1|src/repo2/:gerivdb/REPO2"
    GUARD_MODE="WARN"          # WARN or BLOCK
    TARGET_REPO="ECOS-CLI"

IntentHash: 0xBRG_GENERATE_RULES_20260527
Version: 1.0.0
"""

import sys
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


VERSION = "1.0.0"
INTENT_HASH = "0xBRG_GENERATE_RULES_20260527"

# ── Fallback rules for when manifest is inaccessible ─────────────────────────
FALLBACK_RULES: Dict[str, Dict[str, Any]] = {
    "DevTools": {
        "forbidden_paths": ["src/ecos/", ".ecos/", ".kilocode/", "bin/"],
        "allowed_prefixes": ["devtools/", "fix/", "chore/", "docs/", "refactor/"],
        "redirect_map": {
            "src/ecos/": "gerivdb/ECOS-CLI",
            ".ecos/": "gerivdb/ECOYSTEM",
            ".kilocode/": "gerivdb/ECOS-CLI",
            "bin/": "gerivdb/ECOS-CLI",
        },
    }
}


def load_manifest(manifest_path: str) -> Optional[Dict]:
    """Load the governance manifest YAML."""
    if not HAS_YAML:
        print("[generate_rules] ⚠️  PyYAML not installed — using fallback", file=sys.stderr)
        return None

    p = Path(manifest_path)
    if not p.exists():
        print(f"[generate_rules] ⚠️  Manifest not found: {manifest_path} — using fallback", file=sys.stderr)
        return None

    try:
        with open(p, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"[generate_rules] ⚠️  Error reading manifest: {e} — using fallback", file=sys.stderr)
        return None


def get_repo_config(manifest: Optional[Dict], repo_name: str) -> Dict[str, Any]:
    """Extract branch_routing config for the given repo from the manifest."""
    if manifest is None:
        return FALLBACK_RULES.get(repo_name, {})

    branch_routing = manifest.get("branch_routing", {})
    repositories = branch_routing.get("repositories", {})
    config = repositories.get(repo_name, {})

    if not config:
        print(f"[generate_rules] ⚠️  No routing config for '{repo_name}' in manifest — using fallback", file=sys.stderr)
        return FALLBACK_RULES.get(repo_name, {})

    return {
        "forbidden_paths": config.get("forbidden_paths", []),
        "allowed_prefixes": config.get("allowed_branch_prefixes", []),
        "redirect_map": config.get("redirect_map", {}),
    }


def format_bash_array(items: List[str]) -> str:
    """Format a list as a pipe-separated bash string."""
    if not items:
        return ""
    return "|".join(items)


def format_redirect_map(redirect_map: Dict[str, str]) -> str:
    """Format redirect map as pipe-separated src:dst pairs."""
    if not redirect_map:
        return ""
    return "|".join(f"{src}:{dst}" for src, dst in redirect_map.items())


def generate_rules_sh(config: Dict[str, Any], repo_name: str, guard_mode: str = "WARN") -> str:
    """Generate the rules.sh content as a string."""
    forbidden = format_bash_array(config.get("forbidden_paths", []))
    prefixes = format_bash_array(config.get("allowed_prefixes", []))
    redirect = format_redirect_map(config.get("redirect_map", {}))

    lines = [
        "#!/usr/bin/env bash",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "# rules.sh — Auto-generated by generate_rules.py (BRGS v3.0)",
        "# DO NOT EDIT MANUALLY — Regenerate with: python generate_rules.py <manifest> <repo> <output>",
        f"# Repo: {repo_name}",
        f"# Generated: {__import__('datetime').datetime.now().isoformat()}",
        f"# IntentHash: {INTENT_HASH}",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "",
        f"GUARD_MODE=\"{guard_mode}\"",
        f'FORBIDDEN_PATHS="{forbidden}"',
        f'ALLOWED_PREFIXES="{prefixes}"',
        f'REDIRECT_MAP="{redirect}"',
        f'TARGET_REPO="{repo_name}"',
        "",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <manifest_path> <repo_name> <output_rules.sh>", file=sys.stderr)
        sys.exit(1)

    manifest_path = sys.argv[1]
    repo_name = sys.argv[2]
    output_path = sys.argv[3]

    # Allow GUARD_MODE override from environment
    guard_mode = os.environ.get("BRG_GUARD_MODE", "WARN")

    # Load manifest and extract config
    manifest = load_manifest(manifest_path)
    config = get_repo_config(manifest, repo_name)

    # Generate rules.sh content
    rules_content = generate_rules_sh(config, repo_name, guard_mode)

    # Write output
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(rules_content)
        f.write("\n")

    # Make executable on Unix
    if os.name != "nt":
        os.chmod(output_file, 0o755)

    print(f"[generate_rules] Rules written to {output_path}")
    print(f"[generate_rules]   GUARD_MODE={guard_mode}")
    print(f"[generate_rules]   FORBIDDEN_PATHS: {len(config.get('forbidden_paths', []))} patterns")
    print(f"[generate_rules]   ALLOWED_PREFIXES: {len(config.get('allowed_prefixes', []))} prefixes")


if __name__ == "__main__":
    main()
